config/routes.rb
Rails.application.routes.draw do

  root 'todos#index'
  resources :todos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
    scope :ordered, -> { order("is_finished, created_at desc") }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :load_todo, only: [:edit, :update, :destroy]

  # GET /todos
  # GET /todos.json
  def index
    load_todos
    build_todo
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  # def new
  #   @todo = Todo.new
  # end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    build_todo
    respond_to do |format|
      if @todo.save
        format.html { redirect_to todos_path, notice: 'Todo was successfully created.' }
        # format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :index }
        # format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to todos_path, notice: 'Todo was successfully updated.' }
        # format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :index }
        # format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      # format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def load_todo
      @todo ||= todo_scope.find(params[:id])
    end

    def load_todos
      @todos ||= todo_scope.all
    end

    def build_todo
      @todo ||= todo_scope.new
      @todo.attributes = todo_params
    end

    def set_todo
      @todo = Todo.find(params[:id])
    end

    def todo_scope
      Todo.ordered
    end

    def todo_params
      todo_params = params[:todo]
      todo_params ? todo_params.permit(:title, :remark, :is_finished) : {}
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mytodo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_for @todo do |f| %>
  <p> <%= f.text_field :title, class: 'long_txt' %> </p>
  <p> <%= f.submit "提交", class: 'submit' %> </p>
<% end %>

app/views/todos/edit.html.erb
<div class="box post">
    <h2>修改</h2>
    <%= render 'todos/form' %>
</div>

app/views/todos/index.html.erb
<div class="main box">
  <% if flash[:notice] %>
    <p class="box notice"> <%= flash[:notice] %> </p>
  <% end %>
  <div class="box todos">
    <h2 class="box">待办事项</h2>
    <ul>
      <% @todos.each do |todo| %>
        <li>
          <% if todo.is_finished %>
            <del><%= todo.title %></del>
          <% else %>
            <%= todo.title %>
          <% end %>
          <span class="timeinfo"><%= todo.created_at.to_formatted_s(:db) %></span>
          <% if todo.is_finished %>
            <%= link_to "取消", todo_path(todo.id, todo: {is_finished: false}), method: :patch %>,
          <% else %>
            <%= link_to "完成", todo_path(todo.id, todo: {is_finished: true}), method: :patch %>,
          <% end %>
          <%= link_to "编辑", edit_todo_path(todo.id) %>,
          <%= link_to "删除", todo_path(todo.id), method: :delete %>
        </li>
      <% end %>
    </ul>
  </div>

  <div class="box post">
    <h2>添加</h2>
    <%= render 'todos/form' %>
  </div>

</div>

app/views/todos/new.html.erb
<h1>New Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>